vti_encoding:SR|utf8-nl
vti_timelastmodified:TR|28 Jun 2005 19:36:31 -0000
vti_extenderversion:SR|6.0.2.5516
vti_author:SR|MATRIZ\\jean
vti_modifiedby:SR|MATRIZ\\Jean
vti_timecreated:TR|11 Mar 2005 15:24:00 -0000
vti_nexttolasttimemodified:TR|20 Jun 2005 18:15:54 -0000
vti_cacheddtm:TX|28 Jun 2005 19:36:30 -0000
vti_filesize:IR|80
vti_cachedneedsrewrite:BR|false
vti_cachedhasbots:BR|false
vti_cachedhastheme:BR|false
vti_cachedhasborder:BR|false
vti_charset:SR|windows-1252
vti_backlinkinfo:VX|
